src-openeuler:
  skipped_repo: ["obs-meta"]
  repo_config:
    kata-containers:
      repo: kata-containers
      buddy: kata-containers, kata_integration, kernel
      packages: kata-containers
  arch_config: {}
openeuler:
  skipped_repo: ["community", "release-management"]
  repo_config: {}
  arch_config:
    yocto-poky: [ "arm", "aarch64" ]
    yocto-meta-openeuler: [ "arm", "aarch64" ]
    yocto-embedded-tools: [ "arm", "aarch64" ]